# Generated by Django 3.2.15 on 2022-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmation_number', models.CharField(max_length=45)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
