# Generated by Django 3.2.15 on 2022-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact_contactformemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformemails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformemails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformemails',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
