# Generated by Django 3.2.15 on 2022-10-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221003_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformemails',
            options={'verbose_name_plural': 'ContactFormEmails'},
        ),
    ]
