# Generated by Django 3.2.15 on 2022-10-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contactformemails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformemails',
            options={'verbose_name_plural': 'Contact Form Emails'},
        ),
    ]
