# Generated by Django 3.2.15 on 2022-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221006_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no-image-icon-23499.png', null=True, upload_to=''),
        ),
    ]
