# Generated by Django 3.2.15 on 2022-10-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/no-image-icon-23499.png', null=True, upload_to=''),
        ),
    ]
