# Generated by Django 3.2.15 on 2022-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_img',
            name='img',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
