# Generated by Django 3.2.15 on 2022-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_extra_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_img',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
